name: build and push
on:
  workflow_run:
    workflows: ["Sync Fork"]
    types:
      - completed
  push:
    branches:
      - release/v1.5
    tags:
      - "**"
  pull_request:
  workflow_dispatch: # on button click

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/v1.5

      - name: get_version
        id: get_version
        run: |
          set -e -x
          echo "VERSION=$(git tag -l --contains HEAD | head -n 1)" >> "$GITHUB_OUTPUT"
    
      - name: replace_duration
        run: |
          find . -type f -exec sed -i 's|Add(duration365d \* 10)|Add(duration365d \* 100)|g' {} +
          find . -type f -exec sed -i 's|Add(duration365d)|Add(duration365d \* 100)|g' {} +
          git config --global user.email "yimiaoxiehou@gmail.com"
          git config --global user.name "yimiaoxiehou"
          git add .
          git commit -m "replace cert duration to 36500"
        shell: bash

      - name: Build 
        # skiping fail on warning for now
        run: CI=false make
                  
      - uses: ncipollo/release-action@v1
        with:        
            tag: v1.5
            body: New Release.
            artifacts: "./bin/rke"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
